// Package codegen turns a type-checked AST into a POSIX-ish sh script.
//
// Conventions used by the generated code:
//
//   - Functions return their value via a hidden global named __ret. Callers
//     copy __ret into a fresh temporary the moment they receive it, so nested
//     calls don't clobber each other.
//   - Booleans are stored as 1 (true) or 0 (false), matching the result of
//     POSIX `$((expr))` evaluations. Conversions to/from exit codes happen at
//     `if` boundaries.
//   - All variable expansions are double-quoted to defend against word-splitting
//     and globbing.
//   - Function-local parameter bindings use `local`. POSIX doesn't standardize
//     `local`, but every modern /bin/sh (dash, bash, busybox ash) supports it,
//     and we lose more by polluting global scope than we gain by being strict.
package codegen

import (
	"fmt"
	"strings"

	"github.com/enekosarasola/tartalo/internal/ast"
	"github.com/enekosarasola/tartalo/internal/checker"
	"github.com/enekosarasola/tartalo/internal/loader"
	"github.com/enekosarasola/tartalo/internal/token"
	"github.com/enekosarasola/tartalo/internal/types"
)

type Generator struct {
	info   *checker.TypeInfo
	out    strings.Builder
	indent int
	tmpSeq int

	// currentModule is set while emitting top-level declarations of a module
	// so name-mangling helpers know which module's prefix to use.
	currentModule *loader.Module
	// currentReturnType tracks the declared return type of the function we're
	// emitting. emitReturn consults it to decide whether to also write a
	// `__ret__null` flag (for optional returns) or not.
	currentReturnType types.Type
}

func New(info *checker.TypeInfo) *Generator {
	return &Generator{info: info}
}

// Emit produces the full shell script for a single parsed file. Convenience
// wrapper around EmitModules for the single-file path.
func (g *Generator) Emit(f *ast.File) string {
	m := &loader.Module{File: f, IsEntry: true}
	return g.EmitModules([]*loader.Module{m})
}

// EmitModules walks modules in topological order (deps before dependents) and
// emits a single bundled sh script. Functions and globals from non-entry
// modules are name-mangled (`__mN__name`) so cross-module collisions are
// impossible.
func (g *Generator) EmitModules(modules []*loader.Module) string {
	g.writeLine("#!/bin/sh")
	g.writeLine("# Generated by tartalo. Do not edit by hand.")
	g.writeLine("set -eu")
	g.writeLine("")
	g.writeLine("__ret=\"\"")
	g.writeLine("")

	// Pass 1: function definitions, in topological order (a function may call
	// any other function declared in any loaded module).
	for _, m := range modules {
		g.currentModule = m
		for _, d := range m.File.Decls {
			if fd, ok := d.(*ast.FuncDecl); ok {
				g.emitFunc(fd)
				g.writeLine("")
			}
		}
	}

	// Pass 2: globals, also in topological order.
	for _, m := range modules {
		g.currentModule = m
		for _, d := range m.File.Decls {
			if vd, ok := d.(*ast.VarDecl); ok {
				g.emitVarDecl(vd, false)
			}
		}
	}

	// Find the entry module to invoke its main(), if any.
	var entry *loader.Module
	for _, m := range modules {
		if m.IsEntry {
			entry = m
			break
		}
	}
	g.currentModule = entry
	_ = entry

	// If the entry module declared `main`, invoke it. Imported modules' main
	// (if any) is just an ordinary function reachable by mangled name.
	if entry != nil {
		if _, ok := g.info.Decls[checker.MangledName(entry, "main")]; ok {
			g.writeLine("")
			g.writeLine(`main "$@"`)
		}
	}
	return g.out.String()
}

// --- low-level emit helpers -------------------------------------------------

func (g *Generator) writeLine(s string) {
	for i := 0; i < g.indent; i++ {
		g.out.WriteString("  ")
	}
	g.out.WriteString(s)
	g.out.WriteByte('\n')
}

func (g *Generator) writeLines(lines []string) {
	for _, l := range lines {
		g.writeLine(l)
	}
}

func (g *Generator) tmp(prefix string) string {
	g.tmpSeq++
	return fmt.Sprintf("__%s%d", prefix, g.tmpSeq)
}

// --- function declarations --------------------------------------------------

func (g *Generator) emitFunc(fd *ast.FuncDecl) {
	g.writeLine(shName(checker.MangledName(g.currentModule, fd.Name)) + "() {")
	g.indent++
	// Record the return type so emitReturn knows whether to also write
	// __ret__null. We restore the previous value on exit so nested emits
	// (none today, but future-proof) don't leak.
	prevRet := g.currentReturnType
	if sym := g.info.Decls[checker.MangledName(g.currentModule, fd.Name)]; sym != nil {
		if ft, ok := sym.Type.(*types.Func); ok {
			g.currentReturnType = ft.Result
			// Initialise the return slots before binding any params. If the
			// function falls through without an explicit return, callers
			// see the safe default — null for optional, empty for everything
			// else — instead of stale state from a previous call (or, with
			// `set -u`, an "unbound variable" abort).
			switch r := ft.Result.(type) {
			case *types.Optional:
				g.writeLine(`__ret=""`)
				g.writeLine(`__ret__null=1`)
				_ = r
			case *types.Record:
				for _, f := range r.Fields {
					g.writeLine(fmt.Sprintf(`__ret__%s=""`, f.Name))
					if _, isOpt := f.Type.(*types.Optional); isOpt {
						g.writeLine(fmt.Sprintf(`__ret__%s__null=1`, f.Name))
					}
				}
			default:
				if ft.Result != types.Void {
					g.writeLine(`__ret=""`)
				}
			}
		}
	}
	defer func() { g.currentReturnType = prevRet }()
	// Each parameter may consume one or more positional sh args:
	//   - record: one per field (recursing on optional fields below)
	//   - optional: two (value, then __null flag)
	//   - everything else: one
	pos := 1
	for _, p := range fd.Params {
		paramTy := g.paramType(fd, p.Name)
		switch t := paramTy.(type) {
		case *types.Record:
			for _, f := range t.Fields {
				g.writeLine(fmt.Sprintf(`local %s__%s="$%d"`, shName(p.Name), f.Name, pos))
				pos++
				if _, isOpt := f.Type.(*types.Optional); isOpt {
					g.writeLine(fmt.Sprintf(`local %s__%s__null="$%d"`, shName(p.Name), f.Name, pos))
					pos++
				}
			}
		case *types.Optional:
			g.writeLine(fmt.Sprintf(`local %s="$%d"`, shName(p.Name), pos))
			pos++
			g.writeLine(fmt.Sprintf(`local %s__null="$%d"`, shName(p.Name), pos))
			pos++
		default:
			_ = t
			g.writeLine(fmt.Sprintf(`local %s="$%d"`, shName(p.Name), pos))
			pos++
		}
	}
	for _, s := range fd.Body.Stmts {
		g.emitStmt(s)
	}
	g.indent--
	g.writeLine("}")
}

// paramType resolves the parameter's tartalo type by consulting the function
// symbol the checker recorded.
func (g *Generator) paramType(fd *ast.FuncDecl, paramName string) types.Type {
	sym := g.info.Decls[checker.MangledName(g.currentModule, fd.Name)]
	if sym == nil {
		return types.Invalid
	}
	ft, ok := sym.Type.(*types.Func)
	if !ok {
		return types.Invalid
	}
	for i, p := range fd.Params {
		if p.Name == paramName {
			if i < len(ft.Params) {
				return ft.Params[i]
			}
			return types.Invalid
		}
	}
	return types.Invalid
}

// --- statements -------------------------------------------------------------

func (g *Generator) emitStmt(s ast.Stmt) {
	switch s := s.(type) {
	case *ast.DeclStmt:
		g.emitVarDecl(s.Decl, true)
	case *ast.ExprStmt:
		g.emitExprStmt(s.X)
	case *ast.AssignStmt:
		g.emitAssign(s)
	case *ast.ReturnStmt:
		g.emitReturn(s)
	case *ast.IfStmt:
		g.emitIf(s)
	case *ast.ForStmt:
		g.emitFor(s)
	case *ast.Block:
		for _, st := range s.Stmts {
			g.emitStmt(st)
		}
	case *ast.MatchStmt:
		g.emitMatch(s)
	case *ast.FieldAssignStmt:
		g.emitFieldAssign(s)
	default:
		g.writeLine(fmt.Sprintf("# unsupported stmt: %T", s))
	}
}

func (g *Generator) emitFieldAssign(s *ast.FieldAssignStmt) {
	tv := g.compileExpr(s.Target)
	v := g.compileExpr(s.Value)
	g.writeLines(tv.prologue)
	g.writeLines(v.prologue)
	// If the target field is optional, also write the __null sidecar.
	tt := g.info.Types[s.Target]
	if rec, ok := tt.(*types.Record); ok {
		if f := rec.Lookup(s.Name); f != nil {
			if _, isOpt := f.Type.(*types.Optional); isOpt {
				nullExpr := v.nullCheck
				if nullExpr == "" {
					nullExpr = "0"
				}
				g.writeLine(fmt.Sprintf("%s__%s__null=$((%s))", tv.value, s.Name, nullExpr))
			}
		}
	}
	g.writeLine(fmt.Sprintf("%s__%s=%s", tv.value, s.Name, v.assignmentRHS()))
}

func (g *Generator) emitMatch(s *ast.MatchStmt) {
	v := g.compileExpr(s.Subject)
	g.writeLines(v.prologue)
	subjectVar := g.tmp("subj")
	g.writeLine(fmt.Sprintf("%s=%s", subjectVar, v.assignmentRHS()))
	g.writeLine(fmt.Sprintf("case \"$%s\" in", subjectVar))
	g.indent++
	for _, arm := range s.Cases {
		pats := make([]string, 0, len(arm.Patterns))
		for _, pat := range arm.Patterns {
			pats = append(pats, patternToShCase(pat))
		}
		g.writeLine(strings.Join(pats, "|") + ")")
		g.indent++
		for _, st := range arm.Body.Stmts {
			g.emitStmt(st)
		}
		g.writeLine(";;")
		g.indent--
	}
	g.indent--
	g.writeLine("esac")
}

// patternToShCase renders a tartalo pattern as a sh case-pattern. We single-
// quote string and integer patterns so glob metacharacters match literally.
func patternToShCase(p ast.Pattern) string {
	switch p := p.(type) {
	case *ast.WildcardPattern:
		return "*"
	case *ast.LiteralPattern:
		switch lit := p.Lit.(type) {
		case *ast.IntLit:
			return shSingleQuote(fmt.Sprintf("%d", lit.Value))
		case *ast.BoolLit:
			if lit.Value {
				return "'1'"
			}
			return "'0'"
		case *ast.StringLit:
			var raw strings.Builder
			for _, part := range lit.Parts {
				if c, ok := part.(*ast.StringChunk); ok {
					raw.WriteString(c.Value)
				}
			}
			return shSingleQuote(raw.String())
		}
	}
	return "*"
}

// shSingleQuote wraps `s` in single quotes, escaping any embedded single-quote
// using the standard `'\''` close-reopen idiom. The resulting string matches
// `s` literally inside any sh context that interprets glob metacharacters.
func shSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

func (g *Generator) emitVarDecl(d *ast.VarDecl, local bool) {
	declPrefix := ""
	if d.IsConst {
		declPrefix = "readonly "
	} else if local {
		declPrefix = "local "
	}
	// Top-level globals get the module prefix so two modules can declare a
	// `let counter` without collision in the bundled output.
	target := shName(d.Name)
	if !local {
		target = shName(checker.MangledName(g.currentModule, d.Name))
	}
	// Spot the structural shape of the binding so we know whether to fan it
	// out into multiple shell variables. The declared annotation wins — if
	// the user wrote `: T?` or `: Record`, the binding has that shape even
	// when the initializer is plainly typed.
	if isOptionalTypeAnn(d.TypeAnn) || isOptionalValueType(g.info.Types[d.Value]) {
		g.emitOptVarDecl(d, target, declPrefix)
		return
	}
	if rec, ok := g.info.Types[d.Value].(*types.Record); ok {
		g.emitRecordCopy(target, declPrefix, rec, d.Value)
		return
	}
	v := g.compileExpr(d.Value)
	g.writeLines(v.prologue)
	g.writeLine(fmt.Sprintf("%s%s=%s", declPrefix, target, v.assignmentRHS()))
}

// emitOptVarDecl emits both the value and the __null sidecar for an
// optional-typed variable declaration. Auto-wraps when the RHS is a
// non-optional value of the underlying type.
func (g *Generator) emitOptVarDecl(d *ast.VarDecl, target, declPrefix string) {
	v := g.compileExpr(d.Value)
	g.writeLines(v.prologue)
	nullCheck := v.nullCheck
	if nullCheck == "" {
		// RHS is a non-optional value being auto-wrapped. It is never null.
		nullCheck = "0"
	}
	g.writeLine(fmt.Sprintf("%s%s__null=$((%s))", declPrefix, target, nullCheck))
	g.writeLine(fmt.Sprintf("%s%s=%s", declPrefix, target, v.assignmentRHS()))
}

// isOptionalTypeAnn reports whether a type annotation is `T?`.
func isOptionalTypeAnn(t ast.TypeExpr) bool {
	_, ok := t.(*ast.OptionalType)
	return ok
}

// isOptionalValueType reports whether a (possibly nil) checker type is an
// Optional. nil values count as not-optional.
func isOptionalValueType(t types.Type) bool {
	if t == nil {
		return false
	}
	_, ok := t.(*types.Optional)
	return ok
}

func (g *Generator) emitAssign(s *ast.AssignStmt) {
	sym := g.info.Assigns[s]
	target := shName(s.Name)
	if sym != nil && sym.Module != nil {
		target = shName(checker.MangledName(sym.Module, sym.Name))
	}
	if rec, ok := g.info.Types[s.Value].(*types.Record); ok {
		g.emitRecordCopy(target, "", rec, s.Value)
		return
	}
	if sym != nil {
		if _, isOpt := sym.Type.(*types.Optional); isOpt {
			v := g.compileExpr(s.Value)
			g.writeLines(v.prologue)
			nullExpr := v.nullCheck
			if nullExpr == "" {
				nullExpr = "0"
			}
			g.writeLine(fmt.Sprintf("%s__null=$((%s))", target, nullExpr))
			g.writeLine(fmt.Sprintf("%s=%s", target, v.assignmentRHS()))
			return
		}
	}
	v := g.compileExpr(s.Value)
	g.writeLines(v.prologue)
	g.writeLine(fmt.Sprintf("%s=%s", target, v.assignmentRHS()))
}

func (g *Generator) emitReturn(s *ast.ReturnStmt) {
	if s.Value == nil {
		g.writeLine("return 0")
		return
	}
	if rec, ok := g.info.Types[s.Value].(*types.Record); ok {
		g.emitRecordCopy("__ret", "", rec, s.Value)
		g.writeLine("return 0")
		return
	}
	v := g.compileExpr(s.Value)
	g.writeLines(v.prologue)
	g.writeLine(fmt.Sprintf("__ret=%s", v.assignmentRHS()))
	// If the function's return type is optional, also propagate the null flag.
	// We detect this by whether the value carries one OR the function's
	// declared return type is optional and we're auto-wrapping a non-optional.
	if _, retIsOpt := g.currentReturnType.(*types.Optional); retIsOpt {
		nullExpr := v.nullCheck
		if nullExpr == "" {
			nullExpr = "0"
		}
		g.writeLine(fmt.Sprintf("__ret__null=$((%s))", nullExpr))
	}
	g.writeLine("return 0")
}

func (g *Generator) emitIf(s *ast.IfStmt) {
	cond := g.compileCond(s.Cond)
	g.writeLines(cond.prologue)
	g.writeLine(fmt.Sprintf("if %s; then", cond.test))
	g.indent++
	if len(s.Then.Stmts) == 0 {
		// sh requires at least one command in `then`. `:` is the POSIX no-op.
		g.writeLine(":")
	} else {
		for _, st := range s.Then.Stmts {
			g.emitStmt(st)
		}
	}
	g.indent--
	if s.Else != nil {
		g.writeLine("else")
		g.indent++
		if len(s.Else.Stmts) == 0 {
			g.writeLine(":")
		} else {
			for _, st := range s.Else.Stmts {
				g.emitStmt(st)
			}
		}
		g.indent--
	}
	g.writeLine("fi")
}

func (g *Generator) emitFor(s *ast.ForStmt) {
	switch iter := s.Iter.(type) {
	case *ast.RangeExpr:
		g.emitForRange(s, iter)
	default:
		g.emitForLines(s)
	}
}

func (g *Generator) emitForRange(s *ast.ForStmt, r *ast.RangeExpr) {
	start := g.compileExpr(r.Start)
	end := g.compileExpr(r.End)
	g.writeLines(start.prologue)
	g.writeLines(end.prologue)
	endVar := g.tmp("end")
	g.writeLine(fmt.Sprintf("%s=%s", endVar, end.assignmentRHS()))
	g.writeLine(fmt.Sprintf("%s=%s", shName(s.Var), start.assignmentRHS()))
	g.writeLine(fmt.Sprintf("while [ \"$%s\" -lt \"$%s\" ]; do", shName(s.Var), endVar))
	g.indent++
	for _, st := range s.Body.Stmts {
		g.emitStmt(st)
	}
	g.writeLine(fmt.Sprintf("%s=$((%s + 1))", shName(s.Var), shName(s.Var)))
	g.indent--
	g.writeLine("done")
}

func (g *Generator) emitForLines(s *ast.ForStmt) {
	v := g.compileExpr(s.Iter)
	g.writeLines(v.prologue)
	linesVar := g.tmp("lines")
	g.writeLine(fmt.Sprintf("%s=%s", linesVar, v.assignmentRHS()))
	g.writeLine(fmt.Sprintf("if [ -n \"$%s\" ]; then", linesVar))
	g.indent++
	g.writeLine(fmt.Sprintf("while IFS= read -r %s; do", shName(s.Var)))
	g.indent++
	for _, st := range s.Body.Stmts {
		g.emitStmt(st)
	}
	g.indent--
	g.writeLine(fmt.Sprintf("done <<__TARTALO_LINES__"))
	// heredoc bodies are not indented
	g.out.WriteString(fmt.Sprintf("$%s\n", linesVar))
	g.out.WriteString("__TARTALO_LINES__\n")
	g.indent--
	g.writeLine("fi")
}

func (g *Generator) emitExprStmt(x ast.Expr) {
	// Special cases that have no value: command literals, void calls.
	switch x := x.(type) {
	case *ast.CmdLit:
		// run for side effects, no capture
		cmd, prologue := g.compileCmdString(x)
		g.writeLines(prologue)
		g.writeLine(cmd)
		return
	case *ast.CallExpr:
		v := g.compileCall(x, true)
		g.writeLines(v.prologue)
		// builtins that compile to a single statement put it in prologue and
		// leave value empty; for non-void calls used as a statement we just
		// drop the result.
		if v.value != "" {
			// e.g. the callee is a non-void function whose result is discarded
			g.writeLine(fmt.Sprintf("# discard: %s", v.value))
		}
		return
	}
	v := g.compileExpr(x)
	g.writeLines(v.prologue)
	if v.value != "" {
		g.writeLine(fmt.Sprintf(": %s # discarded value", v.value))
	}
}

// --- expression compilation -------------------------------------------------

// exprValue is the compiled form of an expression: a value reference plus the
// prologue (in source order) needed to make that reference valid.
type exprValue struct {
	prologue []string
	// value is a string in one of three forms depending on form:
	//   formStr   — a sh string suitable inside double-quotes, e.g. `${x}foo` or `Hello`
	//   formArith — a raw arithmetic expression, e.g. `x + 2 * y`
	//   formBool  — a 0/1 arithmetic expression evaluating the bool
	value string
	form  exprForm
	// nullCheck is a sh arithmetic expression that evaluates to 1 if the
	// expression's value is null, else 0. It is set iff the expression has an
	// optional type. For non-optional values it is the empty string.
	nullCheck string
}

type exprForm int

const (
	formStr    exprForm = iota // a quotable string fragment
	formArith                  // a raw arithmetic expression (no leading `$((`)
	formBool                   // a 0/1 arithmetic expression
	formRecord                 // value is a name prefix; the record's fields live as `prefix__<field>`
)

// assignmentRHS yields the right-hand-side text for a `var=...` assignment.
func (v exprValue) assignmentRHS() string {
	switch v.form {
	case formArith, formBool:
		if isSimpleAtom(v.value) {
			return v.value
		}
		return "$((" + v.value + "))"
	default:
		return shQuoteDouble(v.value)
	}
}

// shString returns a fragment suitable for embedding inside an enclosing
// double-quoted string. For arithmetic forms this is `$((expr))`, for string
// forms it is the literal value.
func (v exprValue) shString() string {
	switch v.form {
	case formArith, formBool:
		if isIntLiteral(v.value) {
			return v.value
		}
		return "$((" + v.value + "))"
	default:
		return v.value
	}
}

// isSimpleAtom reports whether the arithmetic value is just a literal int —
// in that case we can use it raw on the RHS without `$(( ))` wrapping.
func isSimpleAtom(s string) bool {
	return isIntLiteral(s)
}

func isIntLiteral(s string) bool {
	if s == "" {
		return false
	}
	i := 0
	if s[0] == '-' {
		if len(s) == 1 {
			return false
		}
		i = 1
	}
	for ; i < len(s); i++ {
		if s[i] < '0' || s[i] > '9' {
			return false
		}
	}
	return true
}

func (g *Generator) compileExpr(e ast.Expr) exprValue {
	switch e := e.(type) {
	case *ast.IntLit:
		return exprValue{value: fmt.Sprintf("%d", e.Value), form: formArith}
	case *ast.BoolLit:
		v := "0"
		if e.Value {
			v = "1"
		}
		return exprValue{value: v, form: formBool}
	case *ast.NullLit:
		// Untyped null. The value form is irrelevant — every consumer that
		// cares about an optional checks `nullCheck` first. We use "" so the
		// generated sh stays valid in both string and arithmetic contexts.
		return exprValue{value: "", form: formStr, nullCheck: "1"}
	case *ast.Ident:
		return g.compileIdent(e)
	case *ast.StringChunk:
		return exprValue{value: e.Value, form: formStr}
	case *ast.StringLit:
		return g.compileStringLit(e)
	case *ast.CmdLit:
		return g.compileCmdLit(e)
	case *ast.UnaryExpr:
		return g.compileUnary(e)
	case *ast.BinaryExpr:
		return g.compileBinary(e)
	case *ast.CallExpr:
		return g.compileCall(e, false)
	case *ast.ArrayLit:
		return g.compileArrayLit(e)
	case *ast.IndexExpr:
		return g.compileIndex(e)
	case *ast.RecordLit:
		return g.compileRecordLit(e, "")
	case *ast.FieldExpr:
		return g.compileFieldExpr(e)
	case *ast.CoalesceExpr:
		return g.compileCoalesce(e)
	case *ast.UnwrapExpr:
		return g.compileUnwrap(e)
	}
	return exprValue{value: fmt.Sprintf("# unsupported expr: %T", e), form: formStr}
}

func (g *Generator) compileArrayLit(a *ast.ArrayLit) exprValue {
	if len(a.Elems) == 0 {
		return exprValue{value: "", form: formStr}
	}
	// Build the array as a newline-joined string. We materialise it via a temp
	// using `printf` so newlines are preserved exactly.
	t := g.tmp("arr")
	var prologue []string
	parts := make([]string, len(a.Elems))
	for i, el := range a.Elems {
		v := g.compileExpr(el)
		prologue = append(prologue, v.prologue...)
		parts[i] = v.shString()
	}
	// Concatenate elements with a literal newline separator. Using a sh
	// here-doc-style string keeps the codegen one-line per join.
	var body strings.Builder
	for i, p := range parts {
		if i > 0 {
			body.WriteByte('\n')
		}
		body.WriteString(p)
	}
	prologue = append(prologue, fmt.Sprintf("%s=\"%s\"", t, body.String()))
	return exprValue{prologue: prologue, value: "${" + t + "}", form: formStr}
}

// compileCoalesce lowers `lhs ?? rhs`. The result is a non-optional value of
// the lhs's element type. We synthesise a temp that gets the underlying lhs
// value when non-null, otherwise the rhs default.
func (g *Generator) compileCoalesce(e *ast.CoalesceExpr) exprValue {
	lv := g.compileExpr(e.Lhs)
	rv := g.compileExpr(e.Rhs)
	prologue := append(append([]string{}, lv.prologue...), rv.prologue...)
	tmp := g.tmp("co")
	// `lv.nullCheck` is set since the checker requires lhs to be optional.
	prologue = append(prologue, fmt.Sprintf(
		`if [ "$%s" = 1 ]; then %s=%s; else %s=%s; fi`,
		lv.nullCheck, tmp, rv.assignmentRHS(), tmp, lv.assignmentRHS()))
	// The result form depends on the underlying element type. Since the
	// checker has already narrowed both sides to the same T, lv.form
	// describes T accurately.
	switch lv.form {
	case formArith, formBool:
		return exprValue{prologue: prologue, value: tmp, form: lv.form}
	default:
		return exprValue{prologue: prologue, value: "${" + tmp + "}", form: formStr}
	}
}

// compileUnwrap lowers `expr!`. If the operand is null the script aborts with
// a diagnostic; otherwise the result is the non-optional value. We use `if`
// rather than `&&` so the test's exit status doesn't fight `set -e`.
func (g *Generator) compileUnwrap(e *ast.UnwrapExpr) exprValue {
	v := g.compileExpr(e.Operand)
	prologue := append([]string{}, v.prologue...)
	prologue = append(prologue, fmt.Sprintf(
		`if [ "$%s" = 1 ]; then printf 'tartalo: forced unwrap of null at %s\n' >&2; exit 1; fi`,
		v.nullCheck, e.OpPos))
	return exprValue{
		prologue: prologue,
		value:    v.value,
		form:     v.form,
	}
}

// compileRecordLit emits the assignments for a record literal. If prefix is
// non-empty, fields are written directly into `prefix__<f>=...` (used when
// the literal is the immediate RHS of a record-typed declaration / return).
// Otherwise a fresh temp prefix is allocated and returned as the value.
func (g *Generator) compileRecordLit(e *ast.RecordLit, prefix string) exprValue {
	rec, _ := g.info.Types[e].(*types.Record)
	if rec == nil {
		return exprValue{value: "# bad record literal", form: formStr}
	}
	if prefix == "" {
		prefix = g.tmp("rec")
	}
	var prologue []string
	for _, f := range rec.Fields {
		var init *ast.FieldInit
		for i := range e.Fields {
			if e.Fields[i].Name == f.Name {
				init = &e.Fields[i]
				break
			}
		}
		if init == nil {
			prologue = append(prologue, fmt.Sprintf(`%s__%s=""`, prefix, f.Name))
			if _, isOpt := f.Type.(*types.Optional); isOpt {
				prologue = append(prologue, fmt.Sprintf(`%s__%s__null=1`, prefix, f.Name))
			}
			continue
		}
		v := g.compileExpr(init.Value)
		prologue = append(prologue, v.prologue...)
		prologue = append(prologue, fmt.Sprintf("%s__%s=%s", prefix, f.Name, v.assignmentRHS()))
		if _, isOpt := f.Type.(*types.Optional); isOpt {
			nullExpr := v.nullCheck
			if nullExpr == "" {
				nullExpr = "0"
			}
			prologue = append(prologue, fmt.Sprintf("%s__%s__null=$((%s))", prefix, f.Name, nullExpr))
		}
	}
	return exprValue{prologue: prologue, value: prefix, form: formRecord}
}

func (g *Generator) compileFieldExpr(e *ast.FieldExpr) exprValue {
	tv := g.compileExpr(e.Target)
	fieldVar := tv.value + "__" + e.Name
	if opt, isOpt := g.info.Types[e].(*types.Optional); isOpt {
		nullVar := fieldVar + "__null"
		switch opt.Elem {
		case types.Number, types.Bool:
			return exprValue{prologue: tv.prologue, value: fieldVar, form: formArith, nullCheck: nullVar}
		default:
			return exprValue{prologue: tv.prologue, value: "${" + fieldVar + "}", form: formStr, nullCheck: nullVar}
		}
	}
	switch g.info.Types[e] {
	case types.Number, types.Bool:
		return exprValue{prologue: tv.prologue, value: fieldVar, form: formArith}
	default:
		return exprValue{prologue: tv.prologue, value: "${" + fieldVar + "}", form: formStr}
	}
}

// emitRecordCopy materialises a record value into the destination prefix,
// generating per-field assignments. Used when assigning one record to another
// or when binding a function-returned record to a variable.
func (g *Generator) emitRecordCopy(targetPrefix, declPrefix string, rec *types.Record, value ast.Expr) {
	// Fast path: record literal as the RHS — write straight into the target.
	if lit, ok := value.(*ast.RecordLit); ok {
		v := g.compileRecordLit(lit, targetPrefix)
		// declPrefix is "local " / "readonly " or "" depending on scope.
		// We rewrite the produced lines to add the prefix.
		for _, line := range v.prologue {
			g.writeLine(declPrefix + line)
		}
		return
	}
	v := g.compileExpr(value)
	g.writeLines(v.prologue)
	for _, f := range rec.Fields {
		src := v.value + "__" + f.Name
		dst := targetPrefix + "__" + f.Name
		g.writeLine(fmt.Sprintf(`%s%s="${%s}"`, declPrefix, dst, src))
		if _, isOpt := f.Type.(*types.Optional); isOpt {
			g.writeLine(fmt.Sprintf(`%s%s__null="${%s__null}"`, declPrefix, dst, src))
		}
	}
}

func (g *Generator) compileIndex(e *ast.IndexExpr) exprValue {
	tv := g.compileExpr(e.Target)
	iv := g.compileExpr(e.Index)
	out := g.tmp("idx")
	prologue := append(append([]string{}, tv.prologue...), iv.prologue...)
	// awk uses 1-based NR; tartalo uses 0-based indexing, so add 1.
	prologue = append(prologue,
		fmt.Sprintf("%s=$(printf '%%s' \"%s\" | awk -v i=%s 'NR==i+1{print; exit}')",
			out, tv.shString(), asArithExpansion(iv)))
	// Render the result form according to the element type so arithmetic on
	// number-array elements doesn't need an extra cast at the use site.
	switch g.info.Types[e] {
	case types.Number, types.Bool:
		return exprValue{prologue: prologue, value: out, form: formArith}
	default:
		return exprValue{prologue: prologue, value: "${" + out + "}", form: formStr}
	}
}

func (g *Generator) compileIdent(id *ast.Ident) exprValue {
	sym := g.info.Uses[id]
	if sym == nil {
		return exprValue{value: "${" + shName(id.Name) + "}", form: formStr}
	}
	name := shName(id.Name)
	if sym.Module != nil {
		name = shName(checker.MangledName(sym.Module, sym.Name))
	}
	if opt, isOpt := sym.Type.(*types.Optional); isOpt {
		// Optional locals/globals live as `name` + `name__null` sidecar.
		nullCheck := name + "__null"
		switch opt.Elem {
		case types.Number, types.Bool:
			return exprValue{value: name, form: formArith, nullCheck: nullCheck}
		default:
			return exprValue{value: "${" + name + "}", form: formStr, nullCheck: nullCheck}
		}
	}
	if _, isRec := sym.Type.(*types.Record); isRec {
		return exprValue{value: name, form: formRecord}
	}
	switch sym.Type {
	case types.Number, types.Bool:
		return exprValue{value: name, form: formArith}
	default:
		return exprValue{value: "${" + name + "}", form: formStr}
	}
}

func (g *Generator) compileStringLit(s *ast.StringLit) exprValue {
	var b strings.Builder
	var prologue []string
	for _, p := range s.Parts {
		switch p := p.(type) {
		case *ast.StringChunk:
			b.WriteString(escapeForDoubleQuoted(p.Value))
		default:
			v := g.compileExpr(p)
			prologue = append(prologue, v.prologue...)
			b.WriteString(v.shString())
		}
	}
	return exprValue{prologue: prologue, value: b.String(), form: formStr}
}

func (g *Generator) compileCmdLit(c *ast.CmdLit) exprValue {
	cmd, prologue := g.compileCmdString(c)
	// Wrap in $(...) so the value is the captured stdout.
	return exprValue{
		prologue: prologue,
		value:    "$(" + cmd + ")",
		form:     formStr,
	}
}

// compileCmdString builds the command-line string for a CmdLit. It returns the
// already-shell-ready command string (suitable for placing after `$(`) plus a
// prologue for any interpolated subexpressions.
func (g *Generator) compileCmdString(c *ast.CmdLit) (string, []string) {
	var b strings.Builder
	var prologue []string
	for _, p := range c.Parts {
		switch p := p.(type) {
		case *ast.StringChunk:
			b.WriteString(p.Value)
		default:
			// Interpolations into a command line need to be embedded as
			// shell-quoted values; the simplest safe form is to evaluate the
			// expression into a temp and use ${tmp}, leaving quoting to the
			// command author.
			v := g.compileExpr(p)
			prologue = append(prologue, v.prologue...)
			t := g.tmp("ci")
			prologue = append(prologue, fmt.Sprintf("%s=%s", t, v.assignmentRHS()))
			b.WriteString("\"${" + t + "}\"")
		}
	}
	return b.String(), prologue
}

func (g *Generator) compileUnary(u *ast.UnaryExpr) exprValue {
	v := g.compileExpr(u.Operand)
	switch u.Op {
	case token.Minus:
		return exprValue{prologue: v.prologue, value: "-(" + asArith(v) + ")", form: formArith}
	case token.Bang:
		return exprValue{prologue: v.prologue, value: "!(" + asArith(v) + ")", form: formBool}
	}
	return exprValue{value: "0", form: formStr}
}

func (g *Generator) compileBinary(b *ast.BinaryExpr) exprValue {
	lt := g.info.Types[b.Lhs]
	rt := g.info.Types[b.Rhs]

	switch b.Op {
	case token.Plus:
		if lt == types.String || rt == types.String {
			lv := g.compileExpr(b.Lhs)
			rv := g.compileExpr(b.Rhs)
			return exprValue{
				prologue: append(append([]string{}, lv.prologue...), rv.prologue...),
				value:    lv.shString() + rv.shString(),
				form:     formStr,
			}
		}
		fallthrough
	case token.Minus, token.Star, token.Slash, token.Percent:
		return g.arithOp(b)
	case token.Eq, token.Neq, token.Lt, token.Lte, token.Gt, token.Gte:
		return g.compareOp(b, lt)
	case token.AndAnd, token.OrOr:
		return g.logicOp(b)
	}
	return exprValue{value: "0", form: formStr}
}

func (g *Generator) arithOp(b *ast.BinaryExpr) exprValue {
	lv := g.compileExpr(b.Lhs)
	rv := g.compileExpr(b.Rhs)
	op := arithSym(b.Op)
	return exprValue{
		prologue: append(append([]string{}, lv.prologue...), rv.prologue...),
		value:    fmt.Sprintf("%s %s %s", arithGroup(lv, b.Op, true), op, arithGroup(rv, b.Op, false)),
		form:     formArith,
	}
}

// tryCompileNullValue is the value-form counterpart to tryCompileNullCond.
// It returns a 1/0 bool for `x == null` / `x != null` (and the trivial
// null-vs-null cases).
func (g *Generator) tryCompileNullValue(b *ast.BinaryExpr) (exprValue, bool) {
	if b.Op != token.Eq && b.Op != token.Neq {
		return exprValue{}, false
	}
	lt := g.info.Types[b.Lhs]
	rt := g.info.Types[b.Rhs]
	var opt ast.Expr
	switch {
	case lt == types.Null && types.IsOptional(rt):
		opt = b.Rhs
	case rt == types.Null && types.IsOptional(lt):
		opt = b.Lhs
	case lt == types.Null && rt == types.Null:
		v := "1"
		if b.Op == token.Neq {
			v = "0"
		}
		return exprValue{value: v, form: formBool}, true
	default:
		return exprValue{}, false
	}
	v := g.compileExpr(opt)
	op := "=="
	if b.Op == token.Neq {
		op = "!="
	}
	return exprValue{
		prologue: v.prologue,
		value:    fmt.Sprintf("%s %s 1", v.nullCheck, op),
		form:     formBool,
	}, true
}

// tryCompileNullCond detects `x == null`, `null == x`, `x != null`, etc. and
// emits a check on the optional side's null flag. Returns ok=true iff the
// comparison was a null comparison.
func (g *Generator) tryCompileNullCond(b *ast.BinaryExpr) (condValue, bool) {
	if b.Op != token.Eq && b.Op != token.Neq {
		return condValue{}, false
	}
	lt := g.info.Types[b.Lhs]
	rt := g.info.Types[b.Rhs]
	// Locate the optional side and the literal-null side.
	var opt ast.Expr
	switch {
	case lt == types.Null && types.IsOptional(rt):
		opt = b.Rhs
	case rt == types.Null && types.IsOptional(lt):
		opt = b.Lhs
	case lt == types.Null && rt == types.Null:
		// `null == null` is always true; `null != null` always false.
		test := "true"
		if b.Op == token.Neq {
			test = "false"
		}
		return condValue{test: test}, true
	default:
		return condValue{}, false
	}
	v := g.compileExpr(opt)
	want := "1"
	if b.Op == token.Neq {
		want = "0"
	}
	return condValue{
		prologue: v.prologue,
		test:     fmt.Sprintf(`[ "$%s" = %s ]`, v.nullCheck, want),
	}, true
}

func (g *Generator) compareOp(b *ast.BinaryExpr, operandType types.Type) exprValue {
	// Null comparison in value position (e.g. `let b = x == null`).
	if v, ok := g.tryCompileNullValue(b); ok {
		return v
	}
	lv := g.compileExpr(b.Lhs)
	rv := g.compileExpr(b.Rhs)
	if operandType == types.String {
		t := g.tmp("scmp")
		var lines []string
		lines = append(lines, lv.prologue...)
		lines = append(lines, rv.prologue...)
		switch b.Op {
		case token.Eq, token.Neq:
			op := "="
			if b.Op == token.Neq {
				op = "!="
			}
			lines = append(lines,
				fmt.Sprintf("if [ \"%s\" %s \"%s\" ]; then %s=1; else %s=0; fi",
					lv.shString(), op, rv.shString(), t, t))
		default:
			lines = append(lines, awkStringCmpAssign(t, b.Op, lv.shString(), rv.shString()))
		}
		return exprValue{prologue: lines, value: t, form: formArith}
	}
	// Numeric / bool: use sh arithmetic comparisons (returns 1 or 0).
	op := arithSym(b.Op)
	return exprValue{
		prologue: append(append([]string{}, lv.prologue...), rv.prologue...),
		value:    fmt.Sprintf("%s %s %s", arithGroup(lv, b.Op, true), op, arithGroup(rv, b.Op, false)),
		form:     formBool,
	}
}

func (g *Generator) logicOp(b *ast.BinaryExpr) exprValue {
	lv := g.compileExpr(b.Lhs)
	rv := g.compileExpr(b.Rhs)
	op := "&&"
	if b.Op == token.OrOr {
		op = "||"
	}
	return exprValue{
		prologue: append(append([]string{}, lv.prologue...), rv.prologue...),
		value:    fmt.Sprintf("%s %s %s", arithGroup(lv, b.Op, true), op, arithGroup(rv, b.Op, false)),
		form:     formBool,
	}
}

func (g *Generator) compileCall(call *ast.CallExpr, isStmt bool) exprValue {
	id, _ := call.Callee.(*ast.Ident)
	if id == nil {
		return exprValue{value: "# bad call", form: formStr}
	}
	sym := g.info.Uses[id]
	if sym == nil {
		return exprValue{value: "# bad call", form: formStr}
	}

	// Compile arguments first, gathering prologues.
	var argVals []exprValue
	var argTypes []types.Type
	var prologue []string
	for _, a := range call.Args {
		av := g.compileExpr(a)
		prologue = append(prologue, av.prologue...)
		argVals = append(argVals, av)
		argTypes = append(argTypes, g.info.Types[a])
	}

	if sym.IsBuiltin {
		return g.compileBuiltinCall(sym, argVals, argTypes, prologue, isStmt)
	}

	// User-defined function: emit `name "arg1" "arg2"`, then snapshot __ret.
	// Use the symbol's module to mangle so cross-module calls hit the right
	// shell function name.
	calleeName := shName(id.Name)
	if sym.Module != nil {
		calleeName = shName(checker.MangledName(sym.Module, sym.Name))
	}
	args := []string{calleeName}
	// The function's declared param types (sym.Type) drive the argument
	// shape, since callers may pass `T` to a `T?` parameter (auto-wrap).
	paramTypes := sym.Type.(*types.Func).Params
	for i, av := range argVals {
		var paramTy types.Type
		if i < len(paramTypes) {
			paramTy = paramTypes[i]
		}
		// Record arguments expand into one positional per field; optional
		// fields contribute their __null sidecar after their value.
		if rec, ok := paramTy.(*types.Record); ok {
			for _, f := range rec.Fields {
				args = append(args, fmt.Sprintf(`"${%s__%s}"`, av.value, f.Name))
				if _, isOpt := f.Type.(*types.Optional); isOpt {
					args = append(args, fmt.Sprintf(`"${%s__%s__null}"`, av.value, f.Name))
				}
			}
			continue
		}
		// Optional parameter: value then null flag.
		if _, isOpt := paramTy.(*types.Optional); isOpt {
			args = append(args, shQuoteDouble(av.shString()))
			nullArg := av.nullCheck
			if nullArg == "" {
				// Auto-wrapped: the actual value is non-null.
				nullArg = "0"
			}
			args = append(args, fmt.Sprintf(`"$((%s))"`, nullArg))
			continue
		}
		args = append(args, shQuoteDouble(av.shString()))
	}
	prologue = append(prologue, strings.Join(args, " "))

	ft := sym.Type.(*types.Func)
	if ft.Result == types.Void {
		return exprValue{prologue: prologue, value: "", form: formStr}
	}
	if rec, ok := ft.Result.(*types.Record); ok {
		// Snapshot __ret__<f> into a fresh prefix so subsequent calls don't clobber.
		t := g.tmp("rec")
		for _, f := range rec.Fields {
			prologue = append(prologue,
				fmt.Sprintf(`%s__%s="${__ret__%s}"`, t, f.Name, f.Name))
			if _, isOpt := f.Type.(*types.Optional); isOpt {
				prologue = append(prologue,
					fmt.Sprintf(`%s__%s__null="${__ret__%s__null}"`, t, f.Name, f.Name))
			}
		}
		return exprValue{prologue: prologue, value: t, form: formRecord}
	}
	if opt, ok := ft.Result.(*types.Optional); ok {
		valTmp := g.tmp("ret")
		nullTmp := g.tmp("retn")
		prologue = append(prologue, fmt.Sprintf(`%s="$__ret"`, valTmp))
		prologue = append(prologue, fmt.Sprintf(`%s="$__ret__null"`, nullTmp))
		switch opt.Elem {
		case types.Number, types.Bool:
			return exprValue{prologue: prologue, value: valTmp, form: formArith, nullCheck: nullTmp}
		default:
			return exprValue{prologue: prologue, value: "${" + valTmp + "}", form: formStr, nullCheck: nullTmp}
		}
	}
	t := g.tmp("ret")
	prologue = append(prologue, fmt.Sprintf("%s=\"$__ret\"", t))
	switch ft.Result {
	case types.Number, types.Bool:
		return exprValue{prologue: prologue, value: t, form: formArith}
	default:
		return exprValue{prologue: prologue, value: "${" + t + "}", form: formStr}
	}
}

func (g *Generator) compileBuiltinCall(sym *checker.Symbol, args []exprValue, argTypes []types.Type, prologue []string, isStmt bool) exprValue {
	switch sym.Name {
	case "echo":
		prologue = append(prologue, fmt.Sprintf("printf '%%s\\n' %s", shQuoteDouble(args[0].shString())))
		return exprValue{prologue: prologue, value: "", form: formStr}
	case "eprint":
		prologue = append(prologue, fmt.Sprintf("printf '%%s\\n' %s 1>&2", shQuoteDouble(args[0].shString())))
		return exprValue{prologue: prologue, value: "", form: formStr}
	case "exit":
		prologue = append(prologue, fmt.Sprintf("exit %s", asArithStr(args[0])))
		return exprValue{prologue: prologue, value: "", form: formStr}
	case "str":
		// number → string; identical underlying representation
		return exprValue{prologue: prologue, value: asArithStr(args[0]), form: formStr}
	case "num":
		// string → number; the value is unquoted so sh's arithmetic parser
		// expands the variable and reads the digits. We trust the user — sh
		// will produce a runtime error at use if the contents aren't numeric.
		t := g.tmp("num")
		prologue = append(prologue,
			fmt.Sprintf("%s=$((%s + 0))", t, args[0].shString()))
		return exprValue{prologue: prologue, value: t, form: formArith}
	case "len":
		t := g.tmp("len")
		argTmp := g.tmp("s")
		prologue = append(prologue, fmt.Sprintf("%s=%s", argTmp, args[0].assignmentRHS()))
		if _, isArr := argTypes[0].(*types.Array); isArr {
			// Arrays serialize as newline-joined strings, so the length is the
			// line count — with an empty-array short-circuit since `wc -l` on
			// "" still reports 1.
			prologue = append(prologue,
				fmt.Sprintf(`if [ -z "$%s" ]; then %s=0; else %s=$(printf '%%s\n' "$%s" | awk 'END{print NR}'); fi`,
					argTmp, t, t, argTmp))
		} else {
			prologue = append(prologue, fmt.Sprintf("%s=${#%s}", t, argTmp))
		}
		return exprValue{prologue: prologue, value: t, form: formArith}
	case "env":
		// env(name): string?
		// We use POSIX `${var+x}` to distinguish "unset" (null) from "set to
		// empty" (non-null empty string). Both branches populate the sidecar
		// `__null` flag so consumers see a consistent optional shape.
		val := g.tmp("env")
		nullVar := g.tmp("envn")
		nameTmp := g.tmp("envname")
		isSet := g.tmp("envset")
		prologue = append(prologue, fmt.Sprintf("%s=%s", nameTmp, args[0].assignmentRHS()))
		prologue = append(prologue, fmt.Sprintf(`eval "%s=\${$%s+1}"`, isSet, nameTmp))
		prologue = append(prologue, fmt.Sprintf(
			`if [ -z "$%s" ]; then %s=""; %s=1; else eval "%s=\$$%s"; %s=0; fi`,
			isSet, val, nullVar, val, nameTmp, nullVar))
		return exprValue{
			prologue:  prologue,
			value:     "${" + val + "}",
			form:      formStr,
			nullCheck: nullVar,
		}
	case "fetch":
		return g.compileFetch(args, prologue)
	case "exec":
		return g.compileExec(args, prologue)
	case "split":
		return g.compileSplit(args, prologue)
	case "join":
		return g.compileJoin(args, prologue)
	case "trim":
		return g.compileTrim(args, prologue)
	case "upper":
		return g.compileTrSimple(args, prologue, "[:lower:]", "[:upper:]")
	case "lower":
		return g.compileTrSimple(args, prologue, "[:upper:]", "[:lower:]")
	case "replace":
		return g.compileReplace(args, prologue)
	case "contains":
		return g.compileContains(args, prologue, "*\"$%s\"*")
	case "startsWith":
		return g.compileContains(args, prologue, "\"$%s\"*")
	case "endsWith":
		return g.compileContains(args, prologue, "*\"$%s\"")
	case "slice":
		return g.compileSlice(args, prologue)

	// --- file I/O ---
	case "readFile":
		return g.compileReadFile(args, prologue)
	case "writeFile":
		return g.compileWriteOrAppendFile(args, prologue, ">")
	case "appendFile":
		return g.compileWriteOrAppendFile(args, prologue, ">>")
	case "removeFile":
		return g.compileSimpleVoidCmd(args, prologue, `rm -f -- "$%s"`)
	case "mkdir":
		return g.compileSimpleVoidCmd(args, prologue, `mkdir -p -- "$%s"`)
	case "listDir":
		return g.compileListDir(args, prologue)
	case "exists":
		return g.compileFsTest(args, prologue, "-e")
	case "isFile":
		return g.compileFsTest(args, prologue, "-f")
	case "isDir":
		return g.compileFsTest(args, prologue, "-d")
	case "readStdin":
		return g.compileReadStdin(prologue)

	// --- path manipulation ---
	case "pathJoin":
		return g.compilePathJoin(args, prologue)
	case "basename":
		return g.compilePathProgram(args, prologue, `basename -- "$%s"`, "bn")
	case "dirname":
		return g.compilePathProgram(args, prologue, `dirname -- "$%s"`, "dn")
	case "extname":
		return g.compileExtname(args, prologue)
	}
	return exprValue{prologue: prologue, value: "# unknown builtin " + sym.Name, form: formStr}
}

// compileExec lowers `exec(cmd)` to a sh invocation that captures stdout,
// stderr, and exit code separately. We dump stdout and stderr to temp files
// and pair the command with `|| code=$?` so that `set -e` in the surrounding
// script doesn't abort us on a non-zero exit. Like fetch, the result is
// snapshotted into a fresh prefix so subsequent calls don't clobber __ret__*.
func (g *Generator) compileExec(args []exprValue, prologue []string) exprValue {
	cmdVar := g.tmp("xcmd")
	stdoutTmp := g.tmp("xout")
	stderrTmp := g.tmp("xerr")
	codeVar := g.tmp("xcode")
	prologue = append(prologue, fmt.Sprintf("%s=%s", cmdVar, args[0].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf(`%s=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%%s' "$$")`, stdoutTmp))
	prologue = append(prologue, fmt.Sprintf(`%s=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%%s' "$$")`, stderrTmp))
	prologue = append(prologue, fmt.Sprintf(`%s=0`, codeVar))
	// Run via `sh -c`. Both `>` and `2>` are quoted so paths with spaces work.
	// The `|| code=$?` clause both records the exit code AND prevents `set -e`
	// from aborting the outer script when the user's command fails.
	prologue = append(prologue, fmt.Sprintf(
		`sh -c "$%s" >"$%s" 2>"$%s" || %s=$?`,
		cmdVar, stdoutTmp, stderrTmp, codeVar))
	prologue = append(prologue, fmt.Sprintf(`__ret__code=$%s`, codeVar))
	prologue = append(prologue, fmt.Sprintf(`__ret__stdout=$(cat "$%s" 2>/dev/null || printf '')`, stdoutTmp))
	prologue = append(prologue, fmt.Sprintf(`__ret__stderr=$(cat "$%s" 2>/dev/null || printf '')`, stderrTmp))
	prologue = append(prologue, `__ret__ok=$(( __ret__code == 0 ))`)
	prologue = append(prologue, fmt.Sprintf(`rm -f "$%s" "$%s"`, stdoutTmp, stderrTmp))
	out := g.tmp("rec")
	for _, f := range []string{"code", "ok", "stdout", "stderr"} {
		prologue = append(prologue, fmt.Sprintf(`%s__%s="${__ret__%s}"`, out, f, f))
	}
	return exprValue{prologue: prologue, value: out, form: formRecord}
}

// --- string stdlib lowering -------------------------------------------------
//
// All of the helpers below pass values to awk via environment variables (the
// ENVIRON array) rather than `-v` to side-step awk's escape rules for newlines
// and backslashes.

func (g *Generator) compileTrSimple(args []exprValue, prologue []string, from, to string) exprValue {
	t := g.tmp("up")
	prologue = append(prologue,
		fmt.Sprintf("%s=$(printf '%%s' %s | tr '%s' '%s')",
			t, shQuoteDouble(args[0].shString()), from, to))
	return exprValue{prologue: prologue, value: "${" + t + "}", form: formStr}
}

func (g *Generator) compileTrim(args []exprValue, prologue []string) exprValue {
	t := g.tmp("trim")
	srcVar := g.tmp("trim_s")
	prologue = append(prologue, fmt.Sprintf("%s=%s", srcVar, args[0].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf(
		`%s=$(%s="$%s" awk 'BEGIN { s = ENVIRON["%s"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%%s", s }')`,
		t, srcVar, srcVar, srcVar))
	return exprValue{prologue: prologue, value: "${" + t + "}", form: formStr}
}

func (g *Generator) compileReplace(args []exprValue, prologue []string) exprValue {
	t := g.tmp("rep")
	sVar := g.tmp("rep_s")
	fVar := g.tmp("rep_f")
	tVar := g.tmp("rep_t")
	prologue = append(prologue, fmt.Sprintf("%s=%s", sVar, args[0].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf("%s=%s", fVar, args[1].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf("%s=%s", tVar, args[2].assignmentRHS()))
	// Literal-substring replace via awk's index(); avoids regex surprises.
	prologue = append(prologue, fmt.Sprintf(
		`%s=$(%s="$%s" %s="$%s" %s="$%s" awk 'BEGIN { s=ENVIRON["%s"]; f=ENVIRON["%s"]; t=ENVIRON["%s"]; if (f=="") { printf "%%s", s; exit }; out=""; while ((i=index(s,f))>0) { out=out substr(s,1,i-1) t; s=substr(s,i+length(f)) }; printf "%%s", out s }')`,
		t,
		sVar, sVar, fVar, fVar, tVar, tVar,
		sVar, fVar, tVar))
	return exprValue{prologue: prologue, value: "${" + t + "}", form: formStr}
}

// compileContains shares an implementation among contains/startsWith/endsWith
// — the only thing that differs is the case-pattern wrapper.
func (g *Generator) compileContains(args []exprValue, prologue []string, patternFmt string) exprValue {
	t := g.tmp("has")
	sVar := g.tmp("has_s")
	pVar := g.tmp("has_p")
	prologue = append(prologue, fmt.Sprintf("%s=%s", sVar, args[0].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf("%s=%s", pVar, args[1].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf("case \"$%s\" in", sVar))
	prologue = append(prologue, fmt.Sprintf("  "+patternFmt+") %s=1 ;;", pVar, t))
	prologue = append(prologue, fmt.Sprintf("  *) %s=0 ;;", t))
	prologue = append(prologue, "esac")
	return exprValue{prologue: prologue, value: t, form: formArith}
}

func (g *Generator) compileSlice(args []exprValue, prologue []string) exprValue {
	t := g.tmp("slc")
	sVar := g.tmp("slc_s")
	prologue = append(prologue, fmt.Sprintf("%s=%s", sVar, args[0].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf(
		`%s=$(%s="$%s" awk -v a=%s -v b=%s 'BEGIN { s=ENVIRON["%s"]; if (a<0) a=0; if (b>length(s)) b=length(s); if (b<=a) { printf ""; exit }; printf "%%s", substr(s, a+1, b-a) }')`,
		t,
		sVar, sVar,
		asArithExpansion(args[1]), asArithExpansion(args[2]),
		sVar))
	return exprValue{prologue: prologue, value: "${" + t + "}", form: formStr}
}

func (g *Generator) compileSplit(args []exprValue, prologue []string) exprValue {
	t := g.tmp("spl")
	sVar := g.tmp("spl_s")
	dVar := g.tmp("spl_d")
	prologue = append(prologue, fmt.Sprintf("%s=%s", sVar, args[0].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf("%s=%s", dVar, args[1].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf(
		`%s=$(%s="$%s" %s="$%s" awk 'BEGIN { s=ENVIRON["%s"]; d=ENVIRON["%s"]; if (d=="") { printf "%%s", s; exit }; pos=1; dl=length(d); first=1; while(1) { rest=substr(s,pos); i=index(rest,d); if (i==0) { if (!first) printf "\n"; printf "%%s", rest; exit }; if (!first) printf "\n"; printf "%%s", substr(s,pos,i-1); pos=pos+i+dl-1; first=0 } }')`,
		t,
		sVar, sVar, dVar, dVar,
		sVar, dVar))
	return exprValue{prologue: prologue, value: "${" + t + "}", form: formStr}
}

// --- file I/O lowering ------------------------------------------------------

// compileReadFile reads an entire file into a string. On any error (missing
// file, permission denied, …) the script aborts with a diagnostic on stderr.
// Trailing newlines in the file content are stripped — that's a property of
// `$(...)` capture and we accept it for v0.
func (g *Generator) compileReadFile(args []exprValue, prologue []string) exprValue {
	pathVar := g.tmp("rf_p")
	contentVar := g.tmp("rf_c")
	prologue = append(prologue, fmt.Sprintf("%s=%s", pathVar, args[0].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf(
		`%s=$(cat -- "$%s") || { printf 'tartalo: readFile: cannot read %%s\n' "$%s" >&2; exit 1; }`,
		contentVar, pathVar, pathVar))
	return exprValue{prologue: prologue, value: "${" + contentVar + "}", form: formStr}
}

// compileWriteOrAppendFile lowers writeFile/appendFile by parameterising the
// redirection operator. Both abort the script on I/O failure.
func (g *Generator) compileWriteOrAppendFile(args []exprValue, prologue []string, redir string) exprValue {
	pathVar := g.tmp("wf_p")
	contentVar := g.tmp("wf_c")
	prologue = append(prologue, fmt.Sprintf("%s=%s", pathVar, args[0].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf("%s=%s", contentVar, args[1].assignmentRHS()))
	op := "writeFile"
	if redir == ">>" {
		op = "appendFile"
	}
	prologue = append(prologue, fmt.Sprintf(
		`printf '%%s' "$%s" %s "$%s" || { printf 'tartalo: %s: cannot write %%s\n' "$%s" >&2; exit 1; }`,
		contentVar, redir, pathVar, op, pathVar))
	return exprValue{prologue: prologue, value: "", form: formStr}
}

// compileSimpleVoidCmd emits a single sh statement for a one-arg-path void
// builtin (removeFile, mkdir). The command is given as a printf format taking
// the path-temp's name.
func (g *Generator) compileSimpleVoidCmd(args []exprValue, prologue []string, cmdFmt string) exprValue {
	pathVar := g.tmp("p")
	prologue = append(prologue, fmt.Sprintf("%s=%s", pathVar, args[0].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf(cmdFmt, pathVar))
	return exprValue{prologue: prologue, value: "", form: formStr}
}

// compileListDir returns the entries of a directory as a string[] (newline-
// joined). Hidden files are included (`-A` excludes only `.` and `..`). On
// error the script aborts.
func (g *Generator) compileListDir(args []exprValue, prologue []string) exprValue {
	pathVar := g.tmp("ld_p")
	listVar := g.tmp("ld_l")
	prologue = append(prologue, fmt.Sprintf("%s=%s", pathVar, args[0].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf(
		`%s=$(ls -1 -A -- "$%s") || { printf 'tartalo: listDir: cannot list %%s\n' "$%s" >&2; exit 1; }`,
		listVar, pathVar, pathVar))
	return exprValue{prologue: prologue, value: "${" + listVar + "}", form: formStr}
}

// compileFsTest emits a 1/0 result based on a `[ -X path ]` test.
func (g *Generator) compileFsTest(args []exprValue, prologue []string, flag string) exprValue {
	pathVar := g.tmp("fst_p")
	resVar := g.tmp("fst_r")
	prologue = append(prologue, fmt.Sprintf("%s=%s", pathVar, args[0].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf(
		`if [ %s "$%s" ]; then %s=1; else %s=0; fi`,
		flag, pathVar, resVar, resVar))
	return exprValue{prologue: prologue, value: resVar, form: formArith}
}

// compileReadStdin reads stdin until EOF and returns it as a string.
func (g *Generator) compileReadStdin(prologue []string) exprValue {
	t := g.tmp("stdin")
	// `cat` with no path reads stdin. Trailing newlines stripped per usual
	// command-substitution semantics.
	prologue = append(prologue, fmt.Sprintf("%s=$(cat)", t))
	return exprValue{prologue: prologue, value: "${" + t + "}", form: formStr}
}

// --- path manipulation ------------------------------------------------------

// compilePathJoin joins two path components, mirroring Node's `path.join`
// semantics for the second-argument-absolute case.
func (g *Generator) compilePathJoin(args []exprValue, prologue []string) exprValue {
	aVar := g.tmp("pj_a")
	bVar := g.tmp("pj_b")
	out := g.tmp("pj_r")
	prologue = append(prologue, fmt.Sprintf("%s=%s", aVar, args[0].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf("%s=%s", bVar, args[1].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf(
		`case "$%s" in /*) %s="$%s" ;; *) case "$%s" in */) %s="$%s$%s" ;; *) %s="$%s/$%s" ;; esac ;; esac`,
		bVar, out, bVar,
		aVar, out, aVar, bVar,
		out, aVar, bVar))
	return exprValue{prologue: prologue, value: "${" + out + "}", form: formStr}
}

// compilePathProgram runs a path utility (basename / dirname) and captures stdout.
func (g *Generator) compilePathProgram(args []exprValue, prologue []string, cmdFmt, label string) exprValue {
	pathVar := g.tmp(label + "_p")
	out := g.tmp(label + "_r")
	prologue = append(prologue, fmt.Sprintf("%s=%s", pathVar, args[0].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf(`%s=$(`+cmdFmt+`)`, append([]any{out}, pathVar)...))
	return exprValue{prologue: prologue, value: "${" + out + "}", form: formStr}
}

// compileExtname returns the extension (including the leading dot) of the
// final component of a path, or "" when the basename has no dot.
func (g *Generator) compileExtname(args []exprValue, prologue []string) exprValue {
	pathVar := g.tmp("ex_p")
	out := g.tmp("ex_r")
	prologue = append(prologue, fmt.Sprintf("%s=%s", pathVar, args[0].assignmentRHS()))
	// Compute basename via shell parameter expansion, then look for a dot.
	prologue = append(prologue, fmt.Sprintf(
		`__ex_b=$(basename -- "$%s"); case "$__ex_b" in *.*) %s=".${__ex_b##*.}" ;; *) %s="" ;; esac`,
		pathVar, out, out))
	return exprValue{prologue: prologue, value: "${" + out + "}", form: formStr}
}

func (g *Generator) compileJoin(args []exprValue, prologue []string) exprValue {
	t := g.tmp("jn")
	sVar := g.tmp("jn_s")
	dVar := g.tmp("jn_d")
	prologue = append(prologue, fmt.Sprintf("%s=%s", sVar, args[0].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf("%s=%s", dVar, args[1].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf(
		`%s=$(%s="$%s" %s="$%s" awk 'BEGIN { s=ENVIRON["%s"]; d=ENVIRON["%s"]; if (s=="") exit; n=split(s, p, "\n"); for (i=1; i<=n; i++) { if (i>1) printf "%%s", d; printf "%%s", p[i] } }')`,
		t,
		sVar, sVar, dVar, dVar,
		sVar, dVar))
	return exprValue{prologue: prologue, value: "${" + t + "}", form: formStr}
}

// compileFetch lowers `fetch(url)` to a curl invocation that captures status
// code, body, and raw response headers separately. The result is a Response
// record snapshotted into a fresh prefix so subsequent calls don't clobber it.
func (g *Generator) compileFetch(args []exprValue, prologue []string) exprValue {
	urlVar := g.tmp("url")
	bodyTmp := g.tmp("fbody")
	hdrsTmp := g.tmp("fhdrs")
	statusTmp := g.tmp("fstatus")
	prologue = append(prologue, fmt.Sprintf("%s=%s", urlVar, args[0].assignmentRHS()))
	prologue = append(prologue, fmt.Sprintf(`%s=$(mktemp 2>/dev/null || printf '/tmp/tt_b_%%s' "$$")`, bodyTmp))
	prologue = append(prologue, fmt.Sprintf(`%s=$(mktemp 2>/dev/null || printf '/tmp/tt_h_%%s' "$$")`, hdrsTmp))
	// curl runs once; -o writes body, -D writes headers, -w prints HTTP status.
	// On any curl failure we treat the status as 0 so the caller can detect it
	// with `r.ok` or `r.status == 0`.
	prologue = append(prologue,
		fmt.Sprintf(`%s=$(curl -sS -L -o "$%s" -D "$%s" -w '%%{http_code}' "$%s" 2>/dev/null) || %s=0`,
			statusTmp, bodyTmp, hdrsTmp, urlVar, statusTmp))
	// Materialise the Response record fields into __ret__*.
	prologue = append(prologue, fmt.Sprintf(`__ret__status=$%s`, statusTmp))
	prologue = append(prologue, fmt.Sprintf(`__ret__body=$(cat "$%s" 2>/dev/null || printf '')`, bodyTmp))
	prologue = append(prologue, fmt.Sprintf(`__ret__headers=$(cat "$%s" 2>/dev/null || printf '')`, hdrsTmp))
	prologue = append(prologue, fmt.Sprintf(`__ret__ok=$(( __ret__status >= 200 && __ret__status < 300 ))`))
	prologue = append(prologue, fmt.Sprintf(`rm -f "$%s" "$%s"`, bodyTmp, hdrsTmp))
	// Snapshot into a fresh prefix, mirroring user-function record returns.
	out := g.tmp("rec")
	for _, f := range []string{"status", "ok", "body", "headers"} {
		prologue = append(prologue, fmt.Sprintf(`%s__%s="${__ret__%s}"`, out, f, f))
	}
	return exprValue{prologue: prologue, value: out, form: formRecord}
}

// --- condition compilation --------------------------------------------------

type condValue struct {
	prologue []string
	test     string // a shell test command (or chain) usable in `if X; then`
}

// compileCond produces a sh test command for an expression in boolean context.
func (g *Generator) compileCond(e ast.Expr) condValue {
	switch e := e.(type) {
	case *ast.BoolLit:
		if e.Value {
			return condValue{test: "true"}
		}
		return condValue{test: "false"}
	case *ast.UnaryExpr:
		if e.Op == token.Bang {
			inner := g.compileCond(e.Operand)
			// POSIX rejects stacked `!` (e.g. `! ! cmd`). When the inner test
			// already starts with a `!`, wrap it in a brace group so the outer
			// negation applies to a compound command instead.
			test := inner.test
			if strings.HasPrefix(test, "!") {
				test = "{ " + test + "; }"
			}
			return condValue{prologue: inner.prologue, test: "! " + test}
		}
	case *ast.BinaryExpr:
		switch e.Op {
		case token.AndAnd:
			lv := g.compileCond(e.Lhs)
			rv := g.compileCond(e.Rhs)
			return condValue{
				prologue: append(append([]string{}, lv.prologue...), rv.prologue...),
				test:     "{ " + lv.test + "; } && { " + rv.test + "; }",
			}
		case token.OrOr:
			lv := g.compileCond(e.Lhs)
			rv := g.compileCond(e.Rhs)
			return condValue{
				prologue: append(append([]string{}, lv.prologue...), rv.prologue...),
				test:     "{ " + lv.test + "; } || { " + rv.test + "; }",
			}
		case token.Eq, token.Neq, token.Lt, token.Lte, token.Gt, token.Gte:
			return g.compileCmpCond(e)
		}
	}
	// Fallback: evaluate to a 0/1 value and test it.
	v := g.compileExpr(e)
	t := g.tmp("cond")
	prologue := append([]string{}, v.prologue...)
	prologue = append(prologue, fmt.Sprintf("%s=%s", t, v.assignmentRHS()))
	return condValue{prologue: prologue, test: fmt.Sprintf("[ \"$%s\" = 1 ]", t)}
}

func (g *Generator) compileCmpCond(b *ast.BinaryExpr) condValue {
	// Null comparisons compile to a check on the optional side's null flag.
	// We dispatch BEFORE compiling both sides because the null literal has no
	// useful value form to compute.
	if cond, ok := g.tryCompileNullCond(b); ok {
		return cond
	}
	lv := g.compileExpr(b.Lhs)
	rv := g.compileExpr(b.Rhs)
	prologue := append(append([]string{}, lv.prologue...), rv.prologue...)
	lt := g.info.Types[b.Lhs]
	if lt == types.String {
		switch b.Op {
		case token.Eq, token.Neq:
			op := "="
			if b.Op == token.Neq {
				op = "!="
			}
			return condValue{
				prologue: prologue,
				test:     fmt.Sprintf("[ \"%s\" %s \"%s\" ]", lv.shString(), op, rv.shString()),
			}
		}
		return condValue{
			prologue: prologue,
			test:     awkStringCmpTest(b.Op, lv.shString(), rv.shString()),
		}
	}
	op := ""
	switch b.Op {
	case token.Eq:
		op = "-eq"
	case token.Neq:
		op = "-ne"
	case token.Lt:
		op = "-lt"
	case token.Lte:
		op = "-le"
	case token.Gt:
		op = "-gt"
	case token.Gte:
		op = "-ge"
	}
	return condValue{
		prologue: prologue,
		test:     fmt.Sprintf("[ \"%s\" %s \"%s\" ]", asArithExpansion(lv), op, asArithExpansion(rv)),
	}
}

// --- helpers ----------------------------------------------------------------

// asArith returns a value's representation suitable for use inside an
// arithmetic context (`$(( ... ))`). For arithmetic forms this is the raw
// expression; for string forms we coerce by trusting the user (sh arithmetic
// will error at runtime if the contents aren't numeric).
func asArith(v exprValue) string {
	switch v.form {
	case formArith, formBool:
		return v.value
	default:
		return v.value
	}
}

// asArithStr returns the value as a quotable shell fragment when the consumer
// expects a string. For arithmetic forms this wraps in $((..)).
func asArithStr(v exprValue) string {
	switch v.form {
	case formArith, formBool:
		return "$((" + v.value + "))"
	default:
		return v.value
	}
}

// asArithExpansion: used inside `[ ... -eq ... ]` where we need a $(( )) form
// or a quoted expansion. For both forms we render arithmetic-as-expansion so
// `[ ` sees a numeric literal at runtime.
func asArithExpansion(v exprValue) string {
	switch v.form {
	case formArith, formBool:
		if isIntLiteral(v.value) {
			return v.value
		}
		return "$((" + v.value + "))"
	default:
		return v.value
	}
}

// awkStringCmpOp returns the awk comparison operator for an ordering token.
func awkStringCmpOp(k token.Kind) string {
	switch k {
	case token.Lt:
		return "<"
	case token.Lte:
		return "<="
	case token.Gt:
		return ">"
	case token.Gte:
		return ">="
	}
	return "=="
}

// awkStringCmpTest emits a shell command (suitable after `if`) that exits 0
// when the string comparison `lhs op rhs` is true. Operands are passed via
// environment variables to sidestep awk's -v escape rules.
func awkStringCmpTest(op token.Kind, lhs, rhs string) string {
	return fmt.Sprintf(
		`__a="%s" __b="%s" awk 'BEGIN{exit !(ENVIRON["__a"] %s ENVIRON["__b"])}'`,
		lhs, rhs, awkStringCmpOp(op))
}

// awkStringCmpAssign emits a shell statement that sets `target` to 1 (true) or
// 0 (false) for the string comparison `lhs op rhs`.
func awkStringCmpAssign(target string, op token.Kind, lhs, rhs string) string {
	return fmt.Sprintf(
		`%s=$(__a="%s" __b="%s" awk 'BEGIN{print (ENVIRON["__a"] %s ENVIRON["__b"]) ? 1 : 0}')`,
		target, lhs, rhs, awkStringCmpOp(op))
}

// arithPrec gives operator precedence in sh arithmetic. Higher binds tighter.
// We mirror the table in POSIX so we only emit parentheses where actually
// needed.
func arithPrec(k token.Kind) int {
	switch k {
	case token.OrOr:
		return 1
	case token.AndAnd:
		return 2
	case token.Eq, token.Neq:
		return 3
	case token.Lt, token.Lte, token.Gt, token.Gte:
		return 4
	case token.Plus, token.Minus:
		return 5
	case token.Star, token.Slash, token.Percent:
		return 6
	}
	return 100
}

// arithGroup returns the value formatted for use as one operand of `op`,
// adding parentheses only if the inner expression's precedence is lower than
// `op`'s. `leftSide` distinguishes left- vs right-hand operands so we get
// correct grouping for left-associative operators.
func arithGroup(v exprValue, op token.Kind, leftSide bool) string {
	switch v.form {
	case formArith, formBool:
		// Detect a binary operator at the top of v.value by looking for the
		// substring of any operator we may have produced. This is a heuristic;
		// we err on the side of adding parens when uncertain.
		inner, ok := topArithOp(v.value)
		if ok {
			outerP := arithPrec(op)
			innerP := arithPrec(inner)
			needParen := innerP < outerP
			if !needParen && innerP == outerP && !leftSide {
				// right-hand side of a same-precedence left-assoc op needs parens.
				needParen = true
			}
			if needParen {
				return "(" + v.value + ")"
			}
		}
		return v.value
	default:
		// String forms appear here only via asArith; quote-safe rendering.
		return v.value
	}
}

// topArithOp tries to identify the outermost binary operator in a value the
// codegen produced. It only handles values produced by arithOp/logicOp above —
// terminals (numbers, identifiers, parenthesized groups) return false.
func topArithOp(value string) (token.Kind, bool) {
	// Skip a leading `!` (unary).
	s := value
	if strings.HasPrefix(s, "!(") {
		return token.Bang, true
	}
	// Walk the string respecting parens and find a top-level operator.
	depth := 0
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '(' {
			depth++
			continue
		}
		if c == ')' {
			depth--
			continue
		}
		if depth != 0 {
			continue
		}
		// 2-char operators first
		if i+1 < len(s) {
			two := s[i : i+2]
			switch two {
			case "==":
				return token.Eq, true
			case "!=":
				return token.Neq, true
			case "<=":
				return token.Lte, true
			case ">=":
				return token.Gte, true
			case "&&":
				return token.AndAnd, true
			case "||":
				return token.OrOr, true
			}
		}
		switch c {
		case '+':
			return token.Plus, true
		case '-':
			// could be unary; if it's the first char, treat as terminal
			if i == 0 {
				continue
			}
			return token.Minus, true
		case '*':
			return token.Star, true
		case '/':
			return token.Slash, true
		case '%':
			return token.Percent, true
		case '<':
			return token.Lt, true
		case '>':
			return token.Gt, true
		}
	}
	return 0, false
}

func arithSym(k token.Kind) string {
	switch k {
	case token.Plus:
		return "+"
	case token.Minus:
		return "-"
	case token.Star:
		return "*"
	case token.Slash:
		return "/"
	case token.Percent:
		return "%"
	case token.Eq:
		return "=="
	case token.Neq:
		return "!="
	case token.Lt:
		return "<"
	case token.Lte:
		return "<="
	case token.Gt:
		return ">"
	case token.Gte:
		return ">="
	}
	return "?"
}

// shName maps a tartalo identifier to a sh variable/function name. For now
// the mapping is identity, but reserved sh names get a __t_ prefix.
func shName(name string) string {
	if shReserved[name] {
		return "__t_" + name
	}
	return name
}

var shReserved = map[string]bool{
	"if": true, "then": true, "else": true, "fi": true,
	"for": true, "do": true, "done": true,
	"while": true, "until": true, "case": true, "esac": true,
	"function": true, "return": true,
	"local": true, "export": true, "readonly": true,
	"true": true, "false": true,
	"in": true, "select": true, "time": true,
}

// shQuoteDouble wraps `body` in double quotes, escaping the four characters
// that have meaning inside double-quoted strings.
func shQuoteDouble(body string) string {
	return "\"" + body + "\""
}

// escapeForDoubleQuoted escapes literal text so it can be embedded inside a
// double-quoted shell string without the shell reinterpreting it.
func escapeForDoubleQuoted(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch c {
		case '\\', '"', '$', '`':
			b.WriteByte('\\')
			b.WriteByte(c)
		default:
			b.WriteByte(c)
		}
	}
	return b.String()
}
