#!/bin/sh
# Generated by tartalo. Do not edit by hand.
set -eu

__ret=""
__tt_argv=$(if [ $# -gt 0 ]; then for __tt_a in "$@"; do printf '%s\n' "$__tt_a"; done; fi)

main() {
  local fields="${__tt_argv}"
  __s2="${fields}"
  if [ -z "$__s2" ]; then __len1=0; else __len1=$(printf '%s\n' "$__s2" | awk 'END{print NR}'); fi
  if [ "$__len1" -eq 0 ]; then
    printf '%s\n' "usage: tartalo run examples/api.tt -- <field1> [field2] ..."
    printf '%s\n' "   pass jq paths like .name or .owner.login"
    exit $((1))
  fi
  local url="https://api.github.com/repos/microsoft/typescript-go"
  printf '%s\n' "GET ${url}"
  __now4=$(date +%s)
  local started=$((__now4))
  __url5="${url}"
  __fbody6=$(mktemp 2>/dev/null || printf '/tmp/tt_b_%s' "$$")
  __fhdrs7=$(mktemp 2>/dev/null || printf '/tmp/tt_h_%s' "$$")
  __fstatus8=$(curl -sS -L -o "$__fbody6" -D "$__fhdrs7" -w '%{http_code}' "$__url5" 2>/dev/null) || __fstatus8=0
  __ret__status=$__fstatus8
  __ret__body=$(cat "$__fbody6" 2>/dev/null || printf '')
  __ret__headers=$(cat "$__fhdrs7" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__status >= 200 && __ret__status < 300 ))
  rm -f "$__fbody6" "$__fhdrs7"
  __rec9__status="${__ret__status}"
  __rec9__ok="${__ret__ok}"
  __rec9__body="${__ret__body}"
  __rec9__headers="${__ret__headers}"
  local r__status="${__rec9__status}"
  local r__ok="${__rec9__ok}"
  local r__body="${__rec9__body}"
  local r__headers="${__rec9__headers}"
  __now10=$(date +%s)
  local elapsed=$((__now10 - started))
  if ! [ "$r__ok" = 1 ]; then
    printf '%s\n' "request failed (status $((r__status)))" 1>&2
    exit $((1))
  fi
  printf '%s\n' "status: $((r__status))  ($((elapsed))s)"
  __now11=$(date +%s)
  __ft_s13=$((__now11))
  __ft_f14="%Y-%m-%d %H:%M:%S"
  __ft12=$(date -r "$__ft_s13" "+$__ft_f14" 2>/dev/null) || __ft12=$(date -d "@$__ft_s13" "+$__ft_f14" 2>/dev/null) || __ft12=""
  printf '%s\n' "at: ${__ft12}"
  if [ -n "$fields" ]; then
    while IFS= read -r path; do
      local p="${path}"
      __has_s16="${p}"
      __has_p17="."
      case "$__has_s16" in
        "$__has_p17"*) __has15=1 ;;
        *) __has15=0 ;;
      esac
      __cond18=$((__has15))
      if ! [ "$__cond18" = 1 ]; then
        p=".${p}"
      fi
      __jg_j19="${r__body}"
      __jg_p20="${p}"
      if __jg_v21=$(printf '%s' "$__jg_j19" | jq -e -r "$__jg_p20" 2>/dev/null); then __jg_n22=0; else __jg_v21=""; __jg_n22=1; fi
      if [ "$__jg_n22" = 1 ]; then __co23="<missing>"; else __co23="${__jg_v21}"; fi
      printf '%s\n' "${p} = ${__co23}"
    done <<__TARTALO_LINES__
$fields
__TARTALO_LINES__
  fi
}


main "$@"
