#!/bin/sh
# Generated by tartalo. Do not edit by hand.
set -eu

__ret=""

main() {
  local prefix="task"
  (
    printf '%s\n' "${prefix}-a started"
    sleep 1
    printf '%s\n' "${prefix}-a done"
  ) &
  (
    printf '%s\n' "${prefix}-b started"
    sleep 1
    printf '%s\n' "${prefix}-b done"
  ) &
  (
    printf '%s\n' "${prefix}-c started"
    sleep 1
    printf '%s\n' "${prefix}-c done"
  ) &
  wait
  printf '%s\n' "all tasks joined"
}


main "$@"
