#!/bin/sh
# Generated by tartalo. Do not edit by hand.
set -eu
LC_NUMERIC=C
export LC_NUMERIC

__ret=""

add() {
  local a="$1"
  local b="$2"
  __ret=$((a + b))
  return 0
}

sum() {
  local xs="$1"
  local __red_a4="${xs}"
  local __red_r6=0
  local __red_f5="add"
  if [ -n "$__red_a4" ]; then
    while IFS= read -r __tt_iter; do
    "$__red_f5" "$__red_r6" "$__tt_iter"
    __red_r6="$__ret"
  done <<__TT_RED_EOF__
$__red_a4
__TT_RED_EOF__
  fi
  __ret=${__red_r6}
  return 0
}

main() {
  local xs="1
2
3
4"
  local ys="10
20
30
40"
  local __zip_a14="${xs}"
  local __zip_b15="${ys}"
  local __zip_f16="add"
  local __zip_o17=""
  local __zip_i18=1
  if [ -n "$__zip_a14" ] && [ -n "$__zip_b15" ]; then
    while IFS= read -r __tt_x; do
    IFS= read -r __tt_y <&3 || break
    "$__zip_f16" "$__tt_x" "$__tt_y"
    if [ "$__zip_i18" = 1 ]; then __zip_o17="$__ret"; __zip_i18=0; else __zip_o17=$(printf '%s\n%s' "$__zip_o17" "$__ret"); fi
  done 3<<__TT_ZIP_B__ <<__TT_ZIP_A__
$__zip_b15
__TT_ZIP_B__
$__zip_a14
__TT_ZIP_A__
  fi
  local sums="${__zip_o17}"
  printf '%s\n' "zip(xs, ys, add) ="
  if [ -n "$sums" ]; then
    while IFS= read -r s; do
      printf '%s\n' "  $((s))"
    done <<__TARTALO_LINES__
$sums
__TARTALO_LINES__
  fi
  sum "${sums}"
  local __ret19="$__ret"
  printf '%s\n' "total = $((__ret19))"
  local zs="1.0
4.0
9.0
16.0"
  local __awk_in25="${zs}"
  local __awk_o26=""
  if [ -n "$__awk_in25" ]; then __awk_o26=$(printf '%s\n' "$__awk_in25" | awk '{ x = $1 + 0; print (sqrt(x)) }'); fi
  local __awk_in27="${__awk_o26}"
  local __awk_o28=""
  if [ -n "$__awk_in27" ]; then __awk_o28=$(printf '%s\n' "$__awk_in27" | awk '{ x = $1 + 0; print (x + 1) }'); fi
  local roots="${__awk_o28}"
  printf '%s\n' "sqrt(zs) + 1 ="
  if [ -n "$roots" ]; then
    while IFS= read -r r; do
      printf '%s\n' "  ${r}"
    done <<__TARTALO_LINES__
$roots
__TARTALO_LINES__
  fi
}


main "$@"
